// <auto-generated />
namespace MovieRentals_20020992.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update_user_fields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_user_fields));
        
        string IMigrationMetadata.Id
        {
            get { return "202011302140200_update_user_fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
